### ISSUE TITLE
TypeError when chaining assertions after directory()

### ISSUE THREAD

**Issue by walteranderson** [chaijs/chai-fs#23] opened 2016-09-13 21:50 UTC
I'm trying to write an assertion checking that a directory exists and contains some files. Here's what I have:

```
expect(path).to.be.a.directory().and.include.files(fileList);
```

When the tests run, it throws a TypeError:

```
     Uncaught TypeError: expect(...).to.be.a.directory(...).and.include.files is not a function
      at Test.<anonymous> (test/integration/site.spec.js:47:58)
      at Test.assert (node_modules/supertest/lib/test.js:161:6)
      at Server.assert (node_modules/supertest/lib/test.js:131:12)
      at emitCloseNT (net.js:1525:8)
      at _combinedTickCallback (internal/process/next_tick.js:71:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

When I remove the additional `.and.include.files` chain, the test passes successfully:

```
expect(path).to.be.a.directory();
```

It seems there may have been some kind of regression around the `directory()` function. I pulled down the project and ran the tests manually. It stopped after 32 failed tests and they all seem to relate to the directory function.

```
-> failed 32 and passed 967 of 999 tests, left 28 pending (723ms)
```

Is this a problem with my local environment? Can anyone else reproduce this behavior?

Thanks

**Comment by BigstickCarpet** [comment] 2016-09-13 22:35
@walteranderson - I was able to reproduce your issue (32 tests failing) on my local machine running Node 6.1.0 on MacOS.  But then I ran the tests a second time and they all passed.  Every time I ran them after that, they all passed.  I also tested on several other versions of Node (0.12, 4.4, and 5.0) and the tests all passed as well.

So, based on that, I'm guessing it's just a bug in the test initialization logic.  I'll look into it more deeply the next time I get a chance, but that may be a few days because I'm currently traveling on holiday.

**Comment by walteranderson** [comment] 2016-09-14 20:09
Okay I'm also seeing the same behavior after running the tests multiple times.

I believe I've isolated my problem though. Installing the package through npm pulls down the 0.1.0 [released in 2014](https://github.com/chaijs/chai-fs/tree/120a7b12d8ad160e07cbfd1a16c037ba6d8c047c). I can work around this by running `npm install chaijs/chai-fs` to pull the latest from this repository.

Is there a new release planned anytime soon? I'd love to not rely on the absolute bleeding-edge.

**Comment by BigstickCarpet** [comment] 2016-10-11 13:09
PR https://github.com/chaijs/chai-fs/pull/25 fixes this

**Comment by BigstickCarpet** [comment] 2016-10-11 14:36
Just found the **actual** cause of this bug.  It wasn't just that npm hadn't been updated with the latest code.  The problem is that the tests rely on [certain files and directories being created](https://github.com/chaijs/chai-fs/blob/9f20e90798433d9fe1e3238e781d17b9d4878957/test/init.js#L20-L39) first, but the code to do that is inside a `before()` callback, so it happens too late.  I'll submit a PR to fix this by moving the file/directory creation logic outside of the `before()` callback, but leave the [directory assertions](https://github.com/chaijs/chai-fs/blob/9f20e90798433d9fe1e3238e781d17b9d4878957/test/init.js#L27-L31) inside the `before()` callback

**Comment by BigstickCarpet** [comment] 2017-01-05 01:41
Closing this issue, since the problem was fixed back in October.  Please re-open if it's still happening

**Closed by BigstickCarpet** 2017-01-05 01:41 UTC
